---

- name: Get Package Facts
  ansible.builtin.package_facts:

- name: Setup Repositories
  community.general.rhsm_repository:
    state: enabled
    purge: true
    name:
      - "rhel-{{ ansible_distribution_major_version }}-for-x86_64-appstream-rpms"
      - "rhel-{{ ansible_distribution_major_version }}-for-x86_64-baseos-rpms"
  when:
    - ansible_distribution == 'RedHat'
    - "rh-amazon-rhui-client" not in ansible_facts["packages"]
    - "rhui-azure-rhel9" not in ansible_facts["packages"]
    - "rhui-azure-rhel8" not in ansible_facts["packages"]

- name: Install Packages
  ansible.builtin.dnf:
    state: present
    name:
      - rsync
      - osbuild-composer
      - composer-cli
      - cockpit-composer
      - bash-completion
      - firewalld
      - genisoimage
      - httpd
      - syslinux
      - cockpit

- name: RHEL8 specific setup
  when:
    - ansible_distribution in ['RedHat', 'CentOS']
    - ansible_distribution_major_version|int == 8
  block:
    - name: Install pytoml
      ansible.builtin.dnf:
        state: present
        name:
          - python3-pytoml

- name: RHEL9 specific setup
  block:
    - name: Install toml
      ansible.builtin.dnf:
        state: present
        name:
          - python3-toml
  when:
    - ansible_distribution in ['RedHat', 'CentOS']
    - ansible_distribution_major_version|int == 9

- name: Enable Cockpit/Composer/Firewalld/Apache
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: "{{ item }}"
  loop:
    - osbuild-composer.socket
    - cockpit.socket
    - httpd.service
    - firewalld

- name: Enable Firewall Ports for Cockpit/Composer/Apache
  ansible.posix.firewalld:
    permanent: true
    immediate: true 
    service: "{{ item }}"
    state: enabled
  loop:
    - cockpit
    - http
